### ISSUE TITLE
An installation issue on windows via "python -m pip install manim"

### ISSUE THREAD

**Issue by woftom** [ManimCommunity/ManimPango#115] opened 2024-10-28 12:22 UTC
Collecting manim
  Using cached manim-0.14.0-py3-none-any.whl.metadata (10 kB)
Collecting Pillow (from manim)
  Using cached pillow-11.0.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting click>=7.1 (from manim)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting click-default-group (from manim)
  Using cached click_default_group-1.2.4-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting cloup<0.8.0,>=0.7.0 (from manim)
  Using cached cloup-0.7.1-py2.py3-none-any.whl.metadata (7.8 kB)
Collecting colour (from manim)
  Using cached colour-0.1.5-py2.py3-none-any.whl.metadata (18 kB)
Collecting decorator<6.0.0,>=5.0.7 (from manim)
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting isosurfaces==0.1.0 (from manim)
  Using cached isosurfaces-0.1.0-py3-none-any.whl.metadata (2.9 kB)
Collecting manimpango<0.5.0,>=0.4.0.post0 (from manim)
  Using cached ManimPango-0.4.4.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\王钧盛\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\王钧盛\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\王钧盛\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\王钧盛\AppData\Local\Temp\pip-build-env-z3xprmlt\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\王钧盛\AppData\Local\Temp\pip-build-env-z3xprmlt\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\王钧盛\AppData\Local\Temp\pip-build-env-z3xprmlt\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 42, in <module>
        File "<string>", line 38, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by woftom** [comment] 2024-10-28 12:22
Anyone could help?Thanks really a lot!

**Comment by behackl** [comment] 2024-10-28 12:25
Thanks for the report, this is a duplicate of #112 and #114. Will be fixed with the upcoming Manim release (and has already been fixed in ManimPango's codebase).

You can use Python 3.12 in the meantime as a workaround.

**Closed as completed by behackl** 2024-10-28 12:25 UTC
